site_name: 晤言的屋檐
site_url: https://test.example
repo_name: WuYan/blog
repo_url: https://github.com/wuyan1345/blog
edit_uri: tree/master/docs
nav:
  - 前言: preface.md
  - 计算机系统Ⅲ:
    - sys3/index.md
    - Fundamentals of computer system: sys3/topic1.md
  - 后记: postscript.md
  - 那些同在屋檐下避雨的人: friends.md
theme:
  name: material
  font: false
  favicon: assets/title.gif
  logo: assets/roundicon.png
  features:
    - navigation.footer
    - content.code.annotate
    - navigation.tracking
    - navigation.indexes
  palette: 
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: orange
      accent: deep orange
    
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple

extra_css:
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  # - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  # - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - /css/custom.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

copyright: Copyright &copy; 2024 WuYan