site_name: 晤言的屋檐
site_url: http://note.wuy4n.com
repo_name: WuYan/blog
repo_url: https://github.com/wuyan1345/blog
edit_uri: tree/master/docs
theme:
  name: material
  custom_dir: overrides
  font: false
  favicon: assets/title.gif
  logo: assets/roundicon.png
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.indexes
    - navigation.top
  palette: 
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: orange
      accent: deep orange
    
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple

extra_css:
  - css/fonts.css
  - css/custom.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      custom_format: "%d %B %Y"
      timezone: Europe/Amsterdam
      locale: en
      fallback_to_build_date: false
      enable_creation_date: false
      exclude:
        - index.md
        - postscript.md
        - preface.md
        - friends.md
      enabled: true
      strict: true
  - statistics:
      page_check_metadata: count


nav:
  - 前言: preface.md
  - 计算机系统Ⅲ:
    - sys3/index.md
    - Fundamentals of computer system: sys3/topic1.md
    - Instruction-Level Parallelism: sys3/topic2.md
  - 面向对象程序与设计:
    - oop/index.md
    - Introduction: oop/topic1.md
  - 数据库系统:
    - database/index.md
    - Introduction: database/topic1.md
    - Intro to Relational Model: database/topic2.md
    - Introduction to SQL: database/topic3.md
    - Intermediate SQL: database/topic4.md
    - Advanced SQL: database/topic5.md
    - Database Design using the E-R Model: database/topic6.md
    - Normalization: database/topic7.md
  - 正则表达式: others/topic1.md
  - 后记: postscript.md
  - 那些同在屋檐下避雨的人: friends.md

not_in_nav: index.md

copyright: Copyright &copy; 2024 WuYan